title: CodewithShreya
author: GitHub User
email: shreya00117@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Hello people, this is Shreya Gupta. I am an engineering undergrad student in Information Technology. My favourite programming language is Java.

theme : minima

show_excerpts: true # set to false to remove excerpts on the homepage
